- id: '1673297282375'
  alias: Aqara Magic Cube 57
  description: ''
  use_blueprint:
    path: brent/zha-aqara-magic-cube-57-actions.yaml
    input:
      remote: e2b992794ac1cd8385064920a1229909
      four_to_four:
      - type: toggle
        device_id: 719ae53ffd9599a74fd455d0bbf73fc7
        entity_id: light.scissor_light_light
        domain: light
      rotate_right:
      - device_id: 719ae53ffd9599a74fd455d0bbf73fc7
        domain: light
        entity_id: light.scissor_light_light
        type: brightness_increase
      rotate_left:
      - device_id: 719ae53ffd9599a74fd455d0bbf73fc7
        domain: light
        entity_id: light.scissor_light_light
        type: brightness_decrease
      cube_shake:
      - type: toggle
        device_id: 719ae53ffd9599a74fd455d0bbf73fc7
        entity_id: light.scissor_light_light
        domain: light
- id: '1673344342838'
  alias: Motion Detected Hall Light
  description: Turn on hall light after detection of motion in hall
  conditions:
  - condition: template
    value_template: '{{ is_state(''input_boolean.hall_on_manually'', ''off'') }}'
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.ikea_of_sweden_tradfri_motion_sensor
      light_target:
        device_id: 1afb1b014d7c51837d70883d80557a68
      no_motion_wait: 15
      switch_target:
        entity_id:
- id: '1673564705495'
  alias: Turn On Living Room TV with WakeOnLan
  description: ''
  trigger:
  - trigger: device
    device_id: e6595a4eb7ab8b1b0d72c1f7d0527754
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - action: wake_on_lan.send_magic_packet
    data:
      mac: 24:e8:53:cb:07:22
  mode: single
- id: '1674505188829'
  alias: Message on device detection
  description: Send android message
  trigger:
  - trigger: state
    entity_id:
    - device_tracker.dp_2_1_tohmy001949_c2c9
    to: home
  condition: []
  action:
  - action: notify.mobile_app_pixel_5
    data:
      message: Unknow device tracker detected
      title: Device is home
  mode: single
- id: '1674828621361'
  alias: Bedroom light on motion
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.ikea_of_sweden_tradfri_motion_sensor_motion
      light_target:
        device_id: 719ae53ffd9599a74fd455d0bbf73fc7
      no_motion_wait: 10
      switch_target:
        entity_id:
- id: '1675024517327'
  alias: Manually switch hall on
  description: Check if hall switch was flipped on manually
  trigger:
  - trigger: event
    event_type: state_changed
    event_data:
      entity_id: switch.switch_entrance
  condition:
  - condition: template
    value_template: '{{ (trigger.event.data.new_state.context.parent_id is none) and
      (trigger.event.data.new_state.state==''on'') }} '
  action:
  - action: notify.mobile_app_pixel_5
    data:
      message: Hall turned on manually
      title: Hall on
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.hall_on_manually
    data: {}
  - action: notify.lg_webos_tv_oled55g1rla
    data:
      message: 'This is a test '
      title: Test
  mode: single
- id: '1675067022089'
  alias: Switch hall off
  description: Reset hall_on_manually toggle to off
  trigger:
  - trigger: event
    event_type: state_changed
    event_data:
      entity_id: switch.switch_entrance
  condition:
  - condition: template
    value_template: '{{ trigger.event.data.new_state.state==''off'' }}'
  action:
  - action: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.hall_on_manually
  mode: single
- id: '1675202634957'
  alias: Lower volume of Alexa after 4am
  description: ''
  trigger:
  - trigger: time
    at: 04:00:00
  condition: []
  action:
  - action: media_player.volume_set
    data:
      volume_level: 0.2
    target:
      device_id:
      - cbf17e38e92dea93152373478a75b2c3
      - 5ed4d4aebbe5883e7d505690ade33328
      entity_id: media_player.denon_home_left_rear
  mode: single
- id: '1675667435715'
  alias: MiBoxer Forwarder
  description: Forward MiBoxer Commands
  trigger:
  - trigger: mqtt
    topic: milight/updates/0x156/fut091/+
  action:
  - action: mqtt.publish
    data_template:
      topic: milight/commands/0x1156/fut091/{{ trigger.topic.split('/')[4] }}
      payload: '{{ trigger.payload }}'
  initial_state: true
- id: '1675668902993'
  alias: MiBoxer Remote
  description: Control living room lights with MiBoxer remote
  trigger:
  - trigger: mqtt
    topic: milight/commands/0x1156/fut091/+
  condition: []
  action:
  - action: '{% if "state" in trigger.payload_json %} light.turn_{{ trigger.payload_json[''state'']
      | lower }} {% else %} light.turn_on {% endif %}'
    target:
      entity_id: "{% set lights_json = {\n  \"4\": \"light.living\",\n  \"1\": \"light.kitchen_table\",\n
        \ \"3\": \"light.couch\",\n  \"0\": \"light.dining\",\n  \"2\": \"light.hue_spots\"\n
        \ }\n%} {% set light_idx = trigger.topic.split('/')[4]|string %} {{ lights_json[light_idx]
        }}\n"
    data: '{% if "brightness" in trigger.payload_json %} {"brightness": {{ [trigger.payload_json[''brightness'']|int,
      10] | max }} } {% else %} {} {% endif %}'
  mode: single
- id: '1675920317018'
  alias: Going to bed
  description: Turn off living room lights after 3 minutes and turn on light in the
    bedroom
  trigger:
  - trigger: state
    entity_id:
    - input_button.bedtime
  condition: []
  action:
  - action: light.turn_on
    data: {}
    target:
      entity_id: light.scissor_light_light
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    data: {}
    target:
      entity_id:
      - light.couch
      - light.ecodim_bv_ecodim_zigbee_3_0_light
  - action: light.turn_off
    data:
      transition: 45
    target:
      entity_id: light.ecodim_bv_ecodim_zigbee_3_0_light_2
  mode: single
- id: '1676276131427'
  alias: Play BNR
  description: ''
  trigger:
  - trigger: state
    entity_id:
    - input_button.radio
  condition: []
  action:
  - action: media_player.play_media
    target:
      entity_id: media_player.denon_home_right_rear
    data:
      media_content_id: '4'
      media_content_type: favorite
    metadata: {}
  mode: single
- id: '1681892643641'
  alias: Select PS4 input
  description: Change AVR HDMI settings when PS4 is selected
  trigger:
  - trigger: state
    entity_id:
    - media_player.denon_avr_x1700h_2
    attribute: source
    to: PlayStation 4
  condition:
  - condition: state
    entity_id: media_player.denon_avr_x1700h_2
    attribute: source
    state: PlayStation 4
  action:
  - action: rest_command.denon_hdmi_control_off
    data: {}
  mode: single
- id: '1681908931100'
  alias: Select TV Audio Source
  description: Turn on HDMI control when input source is TV Audio
  trigger:
  - trigger: state
    entity_id:
    - media_player.denon_avr_x1700h_2
    attribute: source
    to:
    - CBL/SAT
    - TV Audio
  condition: []
  action:
  - action: rest_command.denon_hdmi_control_on
    data: {}
  mode: single
- id: '1681930635269'
  alias: Switch to HDMI2 for PS4
  description: ''
  trigger:
  - trigger: device
    device_id: 628cd7858c774ec3bf4fe2c20fa9181b
    domain: media_player
    entity_id: media_player.playstation_4
    type: idle
  condition: []
  action:
  - action: media_player.select_source
    data:
      source: Denon Home Theatre
    target:
      device_id: e6595a4eb7ab8b1b0d72c1f7d0527754
  mode: single
- id: '1681931471771'
  alias: Switch to Home after PS4 Off
  description: ''
  trigger:
  - trigger: state
    entity_id:
    - media_player.playstation_4
    to: unknown
  condition: []
  action:
  - action: webostv.button
    data:
      entity_id: media_player.lg_webos_tv_oled55g1rla
      button: HOME
  - action: media_player.select_source
    data:
      source: TV Audio
    target:
      entity_id: media_player.denon_avr_x1700h_2
  mode: single
- id: '1696851993683'
  alias: Warn when CO2 is high
  description: ''
  triggers:
  - entity_id:
    - sensor.climate_children_carbon_dioxide
    above: 950
    trigger: numeric_state
  conditions: []
  actions:
  - data:
      message: 'CO2 too high: passed 950'
      title: CO2 high
      data:
        url: /lovelace/graphs
    action: notify.mobile_app_iphone_8
  - data:
      message: 'CO2 too high: passed 950'
      title: CO2 high
      data:
        clickAction: /lovelace/graphs
    action: notify.mobile_app_galaxy23
  mode: single
- id: '1697085225639'
  alias: Select Radio Station
  description: ''
  trigger:
  - trigger: state
    entity_id:
    - input_select.radio_stations
  condition: []
  action:
  - action: media_player.play_media
    target:
      entity_id: media_player.denon_home_right_rear
    data:
      media_content_id: "{% if is_state('input_select.radio_stations', 'BNR Nieuwsradio')
        %} \n  4\n{% else %} \n  3\n{% endif %}\n"
      media_content_type: favorite
    metadata: {}
  mode: single
- id: '1722932563014'
  alias: Send notification when washer is finished
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.washer_job_state
    to: finish
  conditions: []
  actions:
  - action: notify.mobile_app_iphone_8
    metadata: {}
    data:
      message: Het wasprogramma is klaar.
      title: Wasmachine Klaar
  - action: notify.mobile_app_galaxy23
    metadata: {}
    data:
      title: Wasmachine Klaar
      message: Het wasprogramma is klaar.
  mode: single
- id: late_night_presence_lights_auto_off
  alias: Turn on Living Room Lights Late Night Presence and Auto Off
  description: Turns on lights on presence late at night when dark, turns off after
    1 min of no presence
  triggers:
  - trigger: state
    entity_id: binary_sensor.presence_sensor_fp2_c668_presence_sensor_1
    to: 'on'
  conditions:
  - condition: time
    after: '22:00:00'
    before: 07:00:00
  - condition: state
    entity_id: light.living
    state: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - condition: numeric_state
    entity_id: sensor.presence_sensor_fp2_c668_light_sensor_light_level
    below: 10
  actions:
  - action: light.turn_on
    target:
      entity_id: light.tv_desk
    data:
      brightness_pct: 20
  - wait_for_trigger:
    - trigger: state
      entity_id: binary_sensor.presence_sensor_fp2_c668_presence_sensor_1
      to: 'off'
    continue_on_timeout: false
  - delay:
      minutes: 1
  - action: light.turn_off
    target:
      entity_id: light.tv_desk
    data: {}
  mode: restart
