# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

logger:
  default: error
  # logs:
  #   rflink: debug
  #   homeassistant.components.rflink: debug

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Let's encrypt
# http:
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem

wake_on_lan: # enables `wake_on_lan` integration

rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_55137313931351615261-if00
  wait_for_ack: false
  ignore_devices:
    - newkaku_018c4800_*

switch:
  - platform: rflink
    devices:
      newkaku_01ff9b3a_3:
        name: Switch Entrance
      # newkaku_01b28de6_3:
      #   name: Switch Entrance
      newkaku_01ff9b3a_1:
        name: Switch Coutch
      unitec_5f89_01:
        name: Switch Outside1
      unitec_5f89_02:
        name: Switch Outside2

light:
  - platform: rflink
    automatic_add: false

sensor:
  - platform: rflink
    automatic_add: false

binary_sensor:
  - platform: rflink
    devices:
      newkaku_01b28de6_a:
        name: PIR Entrance
        device_class: motion
        off_delay: 60

rest_command:
  denon_hdmi_control_off:
    url: "https://192.168.179.109:10443/ajax/video/set_config?type=3&data=%3CHDMIControl%3E2%3C%2FHDMIControl%3E"
    verify_ssl: false
  denon_hdmi_control_on:
    url: "https://192.168.179.109:10443/ajax/video/set_config?type=3&data=%3CHDMIControl%3E1%3C%2FHDMIControl%3E"
    verify_ssl: false
